// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMcj_WWTsV0qSWE4Oq1VYOBv2g2XAy0NA',
    appId: '1:186637229156:web:65c87ec1599b6cfc219371',
    messagingSenderId: '186637229156',
    projectId: 'teste-3ac0d',
    authDomain: 'teste-3ac0d.firebaseapp.com',
    storageBucket: 'teste-3ac0d.appspot.com',
    measurementId: 'G-K5WGH7EMHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo6U2-ZWDJIuarkSXqrZavKuHjVegveik',
    appId: '1:186637229156:android:bd600cc73a86677f219371',
    messagingSenderId: '186637229156',
    projectId: 'teste-3ac0d',
    storageBucket: 'teste-3ac0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBywxZn7555RfDI-57-bE7sR_PYenhhduk',
    appId: '1:186637229156:ios:eab163e64cc291ab219371',
    messagingSenderId: '186637229156',
    projectId: 'teste-3ac0d',
    storageBucket: 'teste-3ac0d.appspot.com',
    iosBundleId: 'com.example.appcabelereiro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBywxZn7555RfDI-57-bE7sR_PYenhhduk',
    appId: '1:186637229156:ios:a29bb1ca5c829b1b219371',
    messagingSenderId: '186637229156',
    projectId: 'teste-3ac0d',
    storageBucket: 'teste-3ac0d.appspot.com',
    iosBundleId: 'com.example.appcabelereiro.RunnerTests',
  );
}
